services:
  - type: web
    name: technov8-ai
    env: python
    plan: free
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --preload --bind 0.0.0.0:$PORT
